language: php

php:
    - 5.5

env:
    - SYMFONY_VERSION=2.5.*

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit

notifications:
  email:
    - m.orioli@apperclass.com