language: php

php:
    - 5.5

env:
    - SYMFONY_VERSION=2.5.*

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --no-dev
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - m.orioli@apperclass.com
    - ruben.barilani.dev@gmail.com